package rules;
import cn.raulism.drools.model.Address;
import cn.raulism.drools.model.fact.AddressCheckResult;
import cn.raulism.drools.model.DrlFact;

global java.util.List list

rule "Postcode should be filled with exactly 5 numbers"
    when
        address : Address(null != facts,facts.size > 0)
    then
        for(DrlFact fact : address.getFacts()){
            AddressCheckResult result = new AddressCheckResult();
            fact.setResultDesc(fact.getName()+"====");
            list.add(fact);
        }
		System.out.println("规则中打印日志：校验通过!");
end